In [25]:
import pandas as pd
standings_awards = pd.read_csv('awards_playoffs.csv', index_col=[0])
thisyear_stats = pd.read_csv('thisyear_stats.csv', index_col = [0])

In [26]:
thisyear_stats.dropna(inplace=True)
thisyear_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 694 entries, 0 to 701
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Tm         694 non-null    object
 1   Year       694 non-null    int64
 2   QBOverall  694 non-null    float64
 3   WROverall  694 non-null    float64
 4   RBOverall  694 non-null    float64
 5   D_Overall  694 non-null    float64
dtypes: float64(4), int64(1), object(1)
memory usage: 38.0+ KB

In [27]:
standings_awards.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 702 entries, 0 to 732
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tm                 702 non-null    object
 1   W-L%               702 non-null    float64
 2   Year               702 non-null    int64
 3   R.O.D_record       702 non-null    float64
 4   MVPs               702 non-null    float64
 5   OPOYs              702 non-null    float64
 6   DPOYS              702 non-null    float64
 7   ROY_OFFENSE        702 non-null    float64
 8   ROY_DEFENSE        702 non-null    float64
 9   QBProBowl          702 non-null    float64
 10  ProBowl            702 non-null    float64
 11  1stTeam            702 non-null    float64
 12  2ndTeam            702 non-null    float64
 13  Allpro             702 non-null    float64
 14  Made Championship  702 non-null    float64
 15  Made Superbowl     702 non-null    float64
 16  Won SB             702 non-null    float64
 17  Made Playoffs      702 non-null    float64
dtypes: float64(16), int64(1), object(1)
memory usage: 104.2+ KB

In [28]:
final_df = thisyear_stats.merge(standings_awards, how = 'outer', on = ['Tm', 'Year'])
final_df.dropna(inplace=True)
final_df

,Tm,Year,QBOverall,WROverall,RBOverall,D_Overall,W-L%,R.O.D_record,MVPs,OPOYs,...,ROY_DEFENSE,QBProBowl,ProBowl,1stTeam,2ndTeam,Allpro,Made Championship,Made Superbowl,Won SB,Made Playoffs
0,ARI,2000,0.626506,0.757344,0.815789,0.080645,0.188,0.458333,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ARI,2001,0.905405,0.701416,0.846154,0.161290,0.438,0.729333,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,ARI,2002,0.594595,0.550752,0.696429,0.062500,0.313,0.500333,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ARI,2003,0.601266,0.730216,0.702479,0.218750,0.250,0.604333,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ARI,2004,0.666667,0.755319,0.825397,0.468750,0.375,0.396000,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689,WAS,2017,0.917808,0.693471,0.746575,0.500000,0.438,0.521333,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
690,WAS,2018,0.541667,0.679896,0.937063,0.625000,0.438,0.500333,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
691,WAS,2019,0.557143,0.657353,0.864286,0.265625,0.188,0.437667,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
692,WAS,2020,0.506173,0.655532,0.900000,0.968750,0.438,0.343667,0.0,0.0,...,1.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
693,WAS,2021,0.710843,0.626761,0.973856,0.375000,0.412,0.490000,0.0,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 694 entries, 0 to 693
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Tm                 694 non-null    object
 1   Year               694 non-null    int64
 2   QBOverall          694 non-null    float64
 3   WROverall          694 non-null    float64
 4   RBOverall          694 non-null    float64
 5   D_Overall          694 non-null    float64
 6   W-L%               694 non-null    float64
 7   R.O.D_record       694 non-null    float64
 8   MVPs               694 non-null    float64
 9   OPOYs              694 non-null    float64
 10  DPOYS              694 non-null    float64
 11  ROY_OFFENSE        694 non-null    float64
 12  ROY_DEFENSE        694 non-null    float64
 13  QBProBowl          694 non-null    float64
 14  ProBowl            694 non-null    float64
 15  1stTeam            694 non-null    float64
 16  2ndTeam            694 non-null    float64
 17  Allpro             694 non-null    float64
 18  Made Championship  694 non-null    float64
 19  Made Superbowl     694 non-null    float64
 20  Won SB             694 non-null    float64
 21  Made Playoffs      694 non-null    float64
dtypes: float64(20), int64(1), object(1)
memory usage: 124.7+ KB

In [30]:
X = final_df.drop(['Made Playoffs', 'Tm', 'Year','Made Championship','Made Superbowl','Won SB'],axis =1)
y = final_df['Made Playoffs']

In [31]:
X

,QBOverall,WROverall,RBOverall,D_Overall,W-L%,R.O.D_record,MVPs,OPOYs,DPOYS,ROY_OFFENSE,ROY_DEFENSE,QBProBowl,ProBowl,1stTeam,2ndTeam,Allpro
0,0.626506,0.757344,0.815789,0.080645,0.188,0.458333,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.905405,0.701416,0.846154,0.161290,0.438,0.729333,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
2,0.594595,0.550752,0.696429,0.062500,0.313,0.500333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.601266,0.730216,0.702479,0.218750,0.250,0.604333,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.666667,0.755319,0.825397,0.468750,0.375,0.396000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
689,0.917808,0.693471,0.746575,0.500000,0.438,0.521333,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
690,0.541667,0.679896,0.937063,0.625000,0.438,0.500333,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
691,0.557143,0.657353,0.864286,0.265625,0.188,0.437667,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
692,0.506173,0.655532,0.900000,0.968750,0.438,0.343667,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0,1.0
693,0.710843,0.626761,0.973856,0.375000,0.412,0.490000,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
log_model = LogisticRegression()

In [36]:
log_model.fit(X_train, y_train)

LogisticRegression()

In [37]:
y_pred = log_model.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [39]:
accuracy_score(y_test,y_pred)

0.8803827751196173

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.92      0.89      0.90       133
         1.0       0.82      0.86      0.84        76

    accuracy                           0.88       209
   macro avg       0.87      0.88      0.87       209
weighted avg       0.88      0.88      0.88       209